FROM oven/bun:latest AS build

WORKDIR /app

COPY package.json ./
COPY bun.lock ./
RUN bun install
COPY . . 
RUN bun run build


#FOR PRODUCTION LEVEL
FROM nginx:alpine AS production
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


